# Your personal GitHub token
github_token: aeb088171bc940b2c0a094830fa90401b58e9ab3
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Azia/Tashkent

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: sergeypavleko

# Virtual machine IP
ip: 192.168.99.64

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 512
